import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);

import { Cinzel, Fauna_One, } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shared/Navbar";
import Footer from "@/component/shared/Footer";
import { ToastContainer } from "react-toastify";

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
  weight: ["400", "500", "600", "700"],
});

const faunaOne = Fauna_One({
  subsets: ["latin"],
  variable: "--font-fauna",
  weight: "400",
});

export const metadata = {
  title: "Nestudy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cinzel.variable} ${faunaOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <ToastContainer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
